# -*- coding: utf-8 -*-
"""Assignment3B_Kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExXKZHDmffT2j4lW86BvKJdPvksngOUq
"""

from sklearn.datasets import make_blobs
import numpy as np
import matplotlib.pyplot as plt

# Create blobs
data = make_blobs(n_samples=200, n_features=2, centers=4, cluster_std=1.6, random_state=50)

points = data[0]
labels = data[1]

feature_1 = points[:, 0]
feature_2 = points[:, 1]
plt.subplot(1, 2, 1)
plt.scatter(feature_1, feature_2, c=labels, s=10, cmap='viridis')
plt.title('True Clusters')
plt.xlim(-15, 15)
plt.ylim(-15, 15)

# import the library
from sklearn.cluster import KMeans
# Create the KMeans object and specify its characteristics
k = 6# Adjust this value for each run
kmeans_method = KMeans(n_clusters=k)
kmeans_method.fit(points)

# Predict the cluster for a set of points
labels_predicted = kmeans_method.predict(points)

plt.subplot(1, 2, 2)
plt.scatter(feature_1, feature_2, c=labels_predicted, s=10, cmap='viridis')
plt.title(f'Predicted Clusters for k={k}')  # Shows k in the graph title
plt.xlim(-15, 15)
plt.ylim(-15, 15)

# Save the plot before showing it
plt.savefig(f'clusters_k{k}.png')  # Saves the figure with k in the filename

plt.show()